on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
name: ci
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [22, lts/*, 24]
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - run: git fetch --prune --unshallow
      - run: git config --global user.name 'Actions'
      - run: git config --global user.email 'dummy@example.org'
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm install --engine-strict
      - run: npm test
      - name: Codecov
        uses: codecov/codecov-action@v7
        with:
          env_vars: OS, NODE_VERSION
