on:
  push:
    branches:
      - master
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]
name: ci
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    env:
        OS: ${{ matrix.os }}
        NODE_VERSION: ${{ matrix.node }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: git fetch --prune --unshallow
      - run: git config --global user.name 'Actions'
      - run: git config --global user.email 'dummy@example.org'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: npm install --engine-strict
      - run: npm test
      - run: npm run coverage
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS, NODE_VERSION
